import { chromium } from "playwright";
const BASE = "http://127.0.0.1:8124";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const pageErrors = [];
page.on("pageerror", (e) => pageErrors.push(String(e).slice(0, 300)));
await page.goto(BASE + "/index.html", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(1500);
const tabs = await page.locator("[data-tab]").evaluateAll((els) => els.map((e) => `${e.tagName}|${e.className}|data-tab=${e.getAttribute("data-tab")}|text=${(e.textContent||"").trim().slice(0,12)}`).slice(0, 12));
console.log("data-tab 元素:", tabs);
await page.locator('button[data-tab="lab"]').first().click();
await page.waitForTimeout(3000);
console.log("点击 lab 后 URL hash:", page.url());
const sigkelly = await page.locator(".lab-sigkelly-bar, .lab-sigkelly-zone, [class*='sigkelly' i]").count();
console.log("sigkelly 元素数:", sigkelly);
const bodyText = await page.locator("main").textContent().catch(() => "");
console.log("main 文本前 300:", (bodyText||"").replace(/\s+/g," ").slice(0, 300));
console.log("pageerrors:", pageErrors.slice(0, 8));
await browser.close();
