import { chromium } from "playwright";
const BASE = "http://127.0.0.1:8124";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const pageErrors = [];
page.on("pageerror", (e) => pageErrors.push(String(e).slice(0, 300)));
const resp = await page.goto(BASE + "/index.html", { waitUntil: "domcontentloaded" });
console.log("status:", resp?.status());
console.log("title:", await page.title());
const tabs = await page.locator(".tabs button").allTextContents().catch(() => "[]");
console.log("tabs:", tabs);
console.log("data-tab attrs:", await page.locator("[data-tab]").evaluateAll((els) => els.map((e) => e.tagName + "." + (e.className||"") + "|data-tab=" + e.getAttribute("data-tab")).slice(0, 10)).catch(() => "[]"));
console.log("pageerrors:", pageErrors.slice(0, 6));
await browser.close();
